{
  "openapi": "3.0.3",
  "info": {
    "title": "Category Restful API",
    "description": "Documentation about category",
    "version": "1.0.0"
  },
  "paths": {
    "/categories": {
      "get": {
        "tags": ["categories"],
        "summary": "Get All Categories",
        "description": "",
        "parameters": [
          {
            "required": true,
            "schema": {
              "title": "page",
              "exclusiveMinimum": 0,
              "type": "integer"
            },
            "name": "page",
            "in": "query"
          },
          {
            "required": true,
            "schema": {
              "title": "per_page",
              "exclusiveMinimum": 0,
              "type": "integer"
            },
            "name": "per_page",
            "in": "query"
          },
          {
            "required": false,
            "schema": {
              "title": "q",
              "minLength": 1,
              "type": "string"
            },
            "name": "q",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "Request Success.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schema/ExampleResponse"
                },
                "example": {
                  "status_code": 200,
                  "status": true,
                  "message": "Request Success.",
                  "detail_message": null,
                  "results": {
                    "data": [
                      {
                        "id": 1,
                        "name": "string"
                      }
                    ],
                    "total": 1,
                    "next_num": null,
                    "prev_num": null,
                    "page": 1,
                    "iter_pages": [1]
                  }
                }
              }
            }
          },
          "422": {
            "description": "Unprocessable Entity.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": ""
                }
              }
            }
          }
        }
      },
      "post": {
        "tags": ["categories"],
        "summary": "Create Category",
        "description": "",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schema/CategoryCreateUpdate"
              }
            }
          },
          "required": true
        },
        "responses": {
          "201": {
            "description": "Request Success.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schema/ExampleResponse"
                },
                "example": {
                  "status_code": 201,
                  "status": true,
                  "message": "Request Created.",
                  "detail_message": "Successfully create category.",
                  "results": null
                }
              }
            }
          },
          "400": {
            "description": "Validation Failed.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schema/ExampleResponse"
                },
                "example": {
                  "status_code": 400,
                  "status": false,
                  "message": "Validation Failed.",
                  "detail_message": "The name has already been taken.",
                  "results": null
                }
              }
            }
          },
          "422": {
            "description": "Unprocessable Entity.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": ""
                }
              }
            }
          }
        },
        "security": [
          {
            "AuthJWTCookieAccess": []
          }
        ]
      }
    },
    "/categories/{category_id}": {
      "get": {
        "tags": ["categories"],
        "summary": "Get Category By Id",
        "description": "",
        "parameters": [
          {
            "required": true,
            "schema": {
              "title": "category_id",
              "exclusiveMinimum": 0,
              "type": "integer"
            },
            "name": "category_id",
            "in": "path"
          }
        ],
        "responses": {
          "200": {
            "description": "Request Success.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schema/ExampleResponse"
                },
                "example": {
                  "status_code": 200,
                  "status": true,
                  "message": "Request Success.",
                  "detail_message": null,
                  "results": {
                    "id": 1,
                    "name": "string"
                  }
                }
              }
            }
          },
          "404": {
            "description": "Resource Not Found.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schema/ExampleResponse"
                },
                "example": {
                  "status_code": 404,
                  "status": false,
                  "message": "Resource Not Found.",
                  "detail_message": "Category not found!",
                  "results": null
                }
              }
            }
          },
          "422": {
            "description": "Unprocessable Entity.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": ""
                }
              }
            }
          }
        }
      },
      "put": {
        "tags": ["categories"],
        "summary": "Update Category By Id",
        "description": "",
        "parameters": [
          {
            "required": true,
            "schema": {
              "title": "category_id",
              "exclusiveMinimum": 0,
              "type": "integer"
            },
            "name": "category_id",
            "in": "path"
          },
          {
            "name": "access_token_cookie",
            "in": "cookie",
            "required": false,
            "schema": {
              "title": "access_token_cookie",
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schema/CategoryCreateUpdate"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "Request Success.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schema/ExampleResponse"
                },
                "example": {
                  "status_code": 200,
                  "status": true,
                  "message": "Request Success.",
                  "detail_message": "Successfully update the category.",
                  "results": null
                }
              }
            }
          },
          "400": {
            "description": "Validation Failed.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schema/ExampleResponse"
                },
                "example": {
                  "status_code": 400,
                  "status": false,
                  "message": "Validation Failed.",
                  "detail_message": "The name has already been taken.",
                  "results": null
                }
              }
            }
          },
          "404": {
            "description": "Resource Not Found.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schema/ExampleResponse"
                },
                "example": {
                  "status_code": 404,
                  "status": false,
                  "message": "Resource Not Found.",
                  "detail_message": "Category not found!",
                  "results": null
                }
              }
            }
          },
          "422": {
            "description": "Unprocessable Entity.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": ""
                }
              }
            }
          }
        },
        "security": [
          {
            "AuthJWTCookieAccess": []
          }
        ]
      },
      "delete": {
        "tags": ["categories"],
        "summary": "Delete Category By Id",
        "description": "",
        "parameters": [
          {
            "required": true,
            "schema": {
              "title": "category_id",
              "exclusiveMinimum": 0,
              "type": "integer"
            },
            "name": "category_id",
            "in": "path"
          },
          {
            "name": "access_token_cookie",
            "in": "cookie",
            "required": false,
            "schema": {
              "title": "access_token_cookie",
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Request Success.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schema/ExampleResponse"
                },
                "example": {
                  "status_code": 200,
                  "status": true,
                  "message": "Request Success.",
                  "detail_message": "Successfully delete the category.",
                  "results": null
                }
              }
            }
          },
          "404": {
            "description": "Resource Not Found.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schema/ExampleResponse"
                },
                "example": {
                  "status_code": 404,
                  "status": false,
                  "message": "Resource Not Found.",
                  "detail_message": "Category not found!",
                  "results": null
                }
              }
            }
          },
          "422": {
            "description": "Unprocessable Entity.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": ""
                }
              }
            }
          }
        },
        "security": [
          {
            "AuthJWTCookieAccess": []
          }
        ]
      }
    }
  },
  "components": {
    "securitySchemes": {
      "AuthJWTCookieAccess": {
        "type": "apiKey",
        "in": "header",
        "name": "X-CSRF-TOKEN"
      },
      "AuthJWTCookieRefresh": {
        "type": "apiKey",
        "in": "header",
        "name": "X-CSRF-TOKEN"
      }
    },
    "schema": {
      "ExampleResponse": {
        "title": "ExampleResponse",
        "type": "object",
        "required": ["status_code", "status", "message"],
        "properties": {
          "status_code": {
            "title": "status_code",
            "type": "integer"
          },
          "status": {
            "title": "status",
            "type": "boolean"
          },
          "message": {
            "title": "message",
            "type": "string"
          },
          "detail_message": {
            "title": "detail_message",
            "type": "string"
          },
          "results": {
            "title": "results",
            "type": "object"
          }
        }
      },
      "CategoryCreateUpdate": {
        "title": "CategoryCreateUpdate",
        "type": "object",
        "required": ["name"],
        "properties": {
          "name": {
            "title": "name",
            "maxLength": 100,
            "minLength": 3,
            "type": "string"
          }
        }
      }
    }
  }
}
